name: Deploy XaaS Ops Environment

on:
  workflow_dispatch:
    
jobs:
  deploy-mlz:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to IronBank
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil/ironbank
          username: ${{ secrets.IRONBANK_USERNAME }}
          password: ${{ secrets.IRONBANK_PASSWORD }}

          # docker pull registry1.dso.mil/ironbank/microsoft/azure/mission-landing-zone:mlz-v2022.01.0