name: Deploy XaaS Ops Environment

on:
  workflow_dispatch:
    
jobs:
  deploy-mlz:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Azure/missionlz
      - uses: azure/Login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          environment: 'AzureUSGovernment'

      - name: Deploy Mission Landing Zone
        run: |
          az deployment sub create \
            --name myMlz${{ github.run_number }} \
            --location usgovarizona \
            --template-file ./src/bicep/mlz.bicep \
            --parameters \
              resourcePrefix="tmlz${{ github.run_number }}" \
              deployPolicy="true" \
              policy="IL5"

      - name: Deploy Tier3 Workload Spoke
        run: |
          cd ./src/bicep/add-ons
          az deployment sub show \
            --name myMlz${{ github.run_number }} \
            --query properties.outputs > ./deploymentVariables.json

          cd tier3
          az deployment sub create \
            -n myMlzT3${{ github.run_number }} \
            -f tier3.bicep \
            -l usgovarizona \
            --parameters \
              resourcePrefix="tmlzt3${{ github.run_number }} \
              workloadName=xaasops \
              workloadShortName=xo \
              virtualNetworkAddressPrefix='10.0.125.0/25' "

      - name: Deploy DSVM into T3 Spoke
        run: |
          pwd
          cd ~/src/bicep
          ls -la dsvm.bicep

          az deployment group create \
            --resource-group $(az deployment sub show --name myMlzT3${{ github.run_number }} --query properties.outputs.resourceGroupName.value) \
            --template-file dsvm.bicep \
            --parameters \
              adminUsername=azureadmin \
              vmName=dsvmmlz4 \
              authenticationType=password \
              virtualNetworkName=$(az deployment sub show --name myMlzT3${{ github.run_number }} --query properties.outputs.virtualNetworkName.value) \
              subnetName=subnetDSVM \
              subnetIPRange='10.0.125.32/29' \
              networkSecurityGroupName=NSGDSVM \
              adminPasswordOrKey=${{secrets.DSVM_PASSWORD}}

