name: Deploy XaaS Ops Environment

on:
  workflow_dispatch:
    
jobs:
  deploy-mlz:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: https://github.com/Azure/missionlz.git
      - uses: azure/Login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          environment: 'AzureUSGovernment'
      - run: |
          cd missionlz

          az deployment sub create \
            --name myMlzDeployment \
            --location usgovvirginia \
            --template-file ./src/bicep/mlz.bicep \
            --parameters \
              resourcePrefix="tmmMlz" \
              deployPolicy="true" \
              policy="IL5"